Repository binaryballer33/grace_shopper_e_commerce, pull requests merged in 2024-02, with the labels that each got.

#28 improved card styles, added state indicators, got vite env var working
  README.md
  client/src/App.jsx
  client/src/components/auth/login/LoginStyles.js
  client/src/components/auth/logout/LogoutStyles.js
  client/src/components/auth/profile/ProfileStyles.js
  client/src/components/auth/register/RegisterStyles.js
  client/src/components/index.js
  client/src/components/input/SearchBar.jsx
  client/src/components/orders/OrdersStyles.js
  client/src/components/orders/order/OrderItemStyles.js
  client/src/components/products/Products.jsx
  client/src/components/products/ProductsStyles.js
  client/src/components/products/product/Product.jsx
  client/src/components/products/product/ProductItem.jsx
  client/src/components/products/product/ProductItemStyles.js
  client/src/components/products/product/ProductStyles.js
  client/src/components/state_indicators/Error.jsx
  client/src/components/state_indicators/Loading.jsx
  client/src/utils/constant.js
  client/src/utils/helper_functions.js
  client/test/test.js
  client/vite.config.js
  jest.config.js
  package-lock.json
  package.json
  server/src/server.js
  server/test/test.js
Labels: enhancement

#29 update dummy data, allow user to cancel cart/ checkout, add cart route
  server/src/api/cart.js
  server/src/db/constants.js
  server/src/db/index.js
  server/src/server.js
Labels: enhancement

#31 Shaq
  README.md
  client/src/api/api.js
  client/src/api/orderApi.js
  client/src/api/productApi.js
  client/src/api/userApi.js
  client/src/app/orderSlice.js
  client/src/app/productSlice.js
  client/src/app/store.js
  client/src/app/userSlice.js
  client/src/components/products/Products.jsx
  client/src/components/products/product/Product.jsx
  client/src/components/products/product/ProductItem.jsx
  client/src/main.jsx
  client/src/utils/constant.js
  package-lock.json
  package.json
  server/src/api/product.js
  server/src/api/user.js
  server/src/db/index.js
Labels: enhancement

#30 allows user to create cart and add/remove to/from cart, allows user to update quantity of cart
  server/src/api/cart.js
  server/src/db/index.js
Labels: enhancement

#32 changed folder structure, created login, logout, register components and added theme provider to app
  client/src/App.jsx
  client/src/api/api.js
  client/src/app/store.js
  client/src/app/userSlice.js
  client/src/assets/greenAppleLogo.avif
  client/src/components/auth/create_form/CreateForm.jsx
  client/src/components/auth/login/Login.jsx
  client/src/components/auth/login_form/LoginForm.jsx
  client/src/components/auth/logout/Logout.jsx
  client/src/components/auth/profile/Profile.jsx
  client/src/components/auth/register/Register.jsx
  client/src/components/auth/register_form/RegisterForm.jsx
  client/src/components/cart/Cart.jsx
  client/src/components/index.js
  client/src/components/nav_bar/NavBar.jsx
  client/src/components/products/Products.jsx
  client/src/components/products/product/Product.jsx
  client/src/components/products/product/ProductItem.jsx
  client/src/components/state_indicators/Error.jsx
  client/src/main.jsx
  client/src/utils/constant.js
  client/src/utils/helper_functions.js
  server/src/api/user.js
  server/src/middleware/middleware.js
  server/src/server.js
Labels: enhancement

#35 moved frontend pages to pages folder, created testimonials, contact landing page, added images to seed file
  client/src/App.jsx
  client/src/components/auth/create_form/CreateForm.jsx
  client/src/components/auth/logout/Logout.jsx
  client/src/components/auth/profile/Profile.jsx
  client/src/components/index.js
  client/src/components/navbar/NavBar.jsx
  client/src/components/pages/cart/Cart.jsx
  client/src/components/pages/contact/Contact.jsx
  client/src/components/pages/landing_page/LandingPage.jsx
  client/src/components/pages/orders/Orders.jsx
  client/src/components/pages/orders/order/OrderItem.jsx
  client/src/components/pages/products/Products.jsx
  client/src/components/pages/products/product/Product.jsx
  client/src/components/pages/products/product/ProductItem.jsx
  client/src/components/pages/testimonials/Testimonials.jsx
  server/src/db/constants.js
Labels: enhancement

#38 finished order detail page, profile page and order item component
  client/src/App.jsx
  client/src/api/orderApi.js
  client/src/app/orderSlice.js
  client/src/app/userSlice.js
  client/src/assets/field.avif
  client/src/assets/fruit_market.avif
  client/src/components/auth/logout/Logout.jsx
  client/src/components/auth/profile/Profile.jsx
  client/src/components/index.js
  client/src/components/navbar/NavBar.jsx
  client/src/components/pages/cart/Cart.jsx
  client/src/components/pages/landing_page/LandingPage.jsx
  client/src/components/pages/orders/Orders.jsx
  client/src/components/pages/orders/order/OrderDetails.jsx
  client/src/components/pages/orders/order/OrderItem.jsx
  client/src/components/pages/products/BestSellers.jsx
  client/src/components/pages/products/product/Product.jsx
  client/src/components/pages/products/product/ProductItem.jsx
  client/src/components/pages/testimonials/Testimonials.jsx
  client/src/utils/helper_functions.js
  server/src/api/cart.js
  server/src/db/index.js
Labels: enhancement

#41 fixed broken jsx causing site to not render
  client/src/components/pages/cart/Cart.jsx
Labels: bug, enhancement

#43 Create Contact & Testimonial Page
  client/src/components/pages/contact/Contact.jsx
  client/src/components/pages/contact/ContactCard.jsx
  client/src/components/pages/testimonials/Testimonials.jsx
Labels: enhancement

#44 got product item add/remove buttons working
  client/src/components/auth/profile/Profile.jsx
  client/src/components/pages/cart/Cart.jsx
  client/src/components/pages/checkout/Checkout.jsx
  client/src/components/pages/orders/Orders.jsx
  client/src/components/pages/orders/order/OrderDetails.jsx
  client/src/components/pages/products/product/ProductItem.jsx
  client/src/main.jsx
  client/src/utils/helper_functions.js
  server/src/db/index.js
Labels: enhancement

#46 release and deployment ready
  client/src/App.jsx
  client/src/api/orderApi.js
  client/src/assets/shaq.jpg
  client/src/components/index.js
  client/src/components/pages/cart/Cart.jsx
  client/src/components/pages/contact/Contact.jsx
  client/src/components/pages/contact/ContactCard.jsx
  client/src/components/pages/testimonials/Testimonials.jsx
  server/src/api/cart.js
  server/src/db/index.js
Labels: bug, enhancement

#47 fixed issue where npm run build would fail, needed to update package.json with --config param
  client/src/components/pages/cart/Cart.jsx
  client/src/components/pages/products/product/ProductItem.jsx
  client/vite.config.js
  package.json
Labels: bug

#48 adding npx prisma generate to get client generated on render server
  package.json
Labels: bug

#49 adding optional chaining operator to files to stop profile component from failing when user has no orders
  client/src/components/auth/profile/Profile.jsx
  client/src/components/pages/orders/Orders.jsx
  client/src/components/pages/orders/order/OrderDetails.jsx
  client/src/components/pages/orders/order/OrderItem.jsx
Labels: bug
